require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MustdoListsController do

  # This should return the minimal set of attributes required to create a valid
  # MustdoList. As you add validations to MustdoList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MustdoListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mustdo_lists as @mustdo_lists" do
      mustdo_list = MustdoList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mustdo_lists).should eq([mustdo_list])
    end
  end

  describe "GET show" do
    it "assigns the requested mustdo_list as @mustdo_list" do
      mustdo_list = MustdoList.create! valid_attributes
      get :show, {:id => mustdo_list.to_param}, valid_session
      assigns(:mustdo_list).should eq(mustdo_list)
    end
  end

  describe "GET new" do
    it "assigns a new mustdo_list as @mustdo_list" do
      get :new, {}, valid_session
      assigns(:mustdo_list).should be_a_new(MustdoList)
    end
  end

  describe "GET edit" do
    it "assigns the requested mustdo_list as @mustdo_list" do
      mustdo_list = MustdoList.create! valid_attributes
      get :edit, {:id => mustdo_list.to_param}, valid_session
      assigns(:mustdo_list).should eq(mustdo_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MustdoList" do
        expect {
          post :create, {:mustdo_list => valid_attributes}, valid_session
        }.to change(MustdoList, :count).by(1)
      end

      it "assigns a newly created mustdo_list as @mustdo_list" do
        post :create, {:mustdo_list => valid_attributes}, valid_session
        assigns(:mustdo_list).should be_a(MustdoList)
        assigns(:mustdo_list).should be_persisted
      end

      it "redirects to the created mustdo_list" do
        post :create, {:mustdo_list => valid_attributes}, valid_session
        response.should redirect_to(MustdoList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mustdo_list as @mustdo_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        MustdoList.any_instance.stub(:save).and_return(false)
        post :create, {:mustdo_list => { "title" => "invalid value" }}, valid_session
        assigns(:mustdo_list).should be_a_new(MustdoList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MustdoList.any_instance.stub(:save).and_return(false)
        post :create, {:mustdo_list => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mustdo_list" do
        mustdo_list = MustdoList.create! valid_attributes
        # Assuming there are no other mustdo_lists in the database, this
        # specifies that the MustdoList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MustdoList.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => mustdo_list.to_param, :mustdo_list => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested mustdo_list as @mustdo_list" do
        mustdo_list = MustdoList.create! valid_attributes
        put :update, {:id => mustdo_list.to_param, :mustdo_list => valid_attributes}, valid_session
        assigns(:mustdo_list).should eq(mustdo_list)
      end

      it "redirects to the mustdo_list" do
        mustdo_list = MustdoList.create! valid_attributes
        put :update, {:id => mustdo_list.to_param, :mustdo_list => valid_attributes}, valid_session
        response.should redirect_to(mustdo_list)
      end
    end

    describe "with invalid params" do
      it "assigns the mustdo_list as @mustdo_list" do
        mustdo_list = MustdoList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MustdoList.any_instance.stub(:save).and_return(false)
        put :update, {:id => mustdo_list.to_param, :mustdo_list => { "title" => "invalid value" }}, valid_session
        assigns(:mustdo_list).should eq(mustdo_list)
      end

      it "re-renders the 'edit' template" do
        mustdo_list = MustdoList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MustdoList.any_instance.stub(:save).and_return(false)
        put :update, {:id => mustdo_list.to_param, :mustdo_list => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mustdo_list" do
      mustdo_list = MustdoList.create! valid_attributes
      expect {
        delete :destroy, {:id => mustdo_list.to_param}, valid_session
      }.to change(MustdoList, :count).by(-1)
    end

    it "redirects to the mustdo_lists list" do
      mustdo_list = MustdoList.create! valid_attributes
      delete :destroy, {:id => mustdo_list.to_param}, valid_session
      response.should redirect_to(mustdo_lists_url)
    end
  end

end
